{% set name = "npTDMS" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e65c237e9d50b9b8e162b9c34171353a5ea05f4019c99c3e8ebc00722361cbc

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tdmsinfo = nptdms.tdmsinfo:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - nptdms
  commands:
    - tdmsinfo -h

about:
  home: https://github.com/adamreeve/npTDMS
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Cross-platform, NumPy based module for reading TDMS files produced by LabView.
  description: |
    npTDMS is a cross-platform Python package for reading and writing TDMS
    files as produced by LabVIEW, and is built on top of the numpy package.
    Data read from a TDMS file is stored in numpy arrays, and numpy arrays are
    also used when writing TDMS file.
  doc_url: http://nptdms.readthedocs.io/
  dev_url: https://github.com/adamreeve/npTDMS

extra:
  recipe-maintainers:
    - carlodri
    - lstebel
