{% set name = "npTDMS" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 812a4f369abd3668ed90f2941926c19b0873f106a7993906acf18983318eff1e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tdmsinfo = nptdms.tdmsinfo:main

requirements:
  host:
    - python >=2
    - pip
  run:
    - python >=2
    - numpy

test:
  imports:
    - nptdms
  commands:
    - tdmsinfo -h

about:
  home: https://github.com/adamreeve/npTDMS
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Cross-platform, NumPy based module for reading TDMS files produced by LabView.
  description: |
    npTDMS is a cross-platform Python package for reading and writing TDMS
    files as produced by LabVIEW, and is built on top of the numpy package.
    Data read from a TDMS file is stored in numpy arrays, and numpy arrays are
    also used when writing TDMS file.
  doc_url: http://nptdms.readthedocs.io/
  dev_url: https://github.com/adamreeve/npTDMS

extra:
  recipe-maintainers:
    - carlodri
    - lstebel
