travis:
  secure:
    BINSTAR_TOKEN: B4TO9aiqgmTHE2kMLZC6hPZKn/54E/R1HrtLhNFe9tqlsu+Txq4Iwu5NizFKZ3JNbmQX/uytvtbtHf+X8uPgp4Wh+xiFtLiTrMlOjGPfRfTASUw5INM0b1FNI0r2J2ZfW3jvXXUfHMqoHCu+FIYsEaRlQqH3JUAV+mB/rOpJFxhYJ1itpTimL2iilAHSzoqI0/h02O7Pcwz1mXMmyRa3XhA7pGzB6nHKxo63SryRfKEMQCkUMg9lXJZ/WDYI6bBoiGxI+wanK57O/sPzyF+kxBMi42Y2llCBD3g6yAf2w39F2jNu0pXvK9v4jYBbo4rkzjPcZ1COTafhoaKl3/tPTUq+hckE/cWb5GaY8MiR3Arg0wHjJUgMZAi8KO+P9NjCsFUeZYhCTGOySqyX4bPTlKD4PcVB1rQm3F4ES9gfcorGIcnyLuCWPk75OtWq/AdyrrEENbH1HSf5KHzAbfk20Lv/kpW/q0taW3D0HnuSyMWxDEpYvrTxVeqINcySlYTTA4p5EypQdctJeUz6Iz8qET4PX5SIfJZfmoDkiv70jDZGAY2k0I0uV3p7UPPFFBMNZ+uB8NXAl1s5q6tdomaAS8FzimRjDGbPSsGuIMMTAspHEEcqeholGpRybXFDoPtGY6nYCGwAF+XfE2BmDmKmoQ5nJZSw47VOnSKBakZSAQo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
